function isPlayed(score){return Number.isInteger(score)}
function playerForRound(i){return i%playerNames.length}
function getISOWeek(date){const d=new Date(Date.UTC(date.getUTCFullYear(),date.getUTCMonth(),date.getUTCDate()));const day=d.getUTCDay()||7;d.setUTCDate(d.getUTCDate()+4-day);const y=new Date(Date.UTC(d.getUTCFullYear(),0,1));return{year:d.getUTCFullYear(),week:Math.ceil((((d-y)/86400000)+1)/7)}}
function isoWeekToMonday(year,week){const j=new Date(Date.UTC(year,0,4));const day=j.getUTCDay()||7;const d=new Date(j);d.setUTCDate(j.getUTCDate()-day+1+(week-1)*7);return d}
function addWeeksToISO(year,week,add){const d=isoWeekToMonday(year,week);d.setUTCDate(d.getUTCDate()+add*7);return getISOWeek(d)}
function getSchedule(){return Array.from({length:season.rounds},(_,i)=>{const iso=addWeeksToISO(season.startYear,season.startWeek,i);return{round:i+1,week:iso.week,year:iso.year,playerIndex:playerForRound(i),playerName:playerNames[playerForRound(i)],score:results[i]??null}})}
function buildStats(schedule){return playerNames.map((name,playerIndex)=>{const played=schedule.filter(r=>r.playerIndex===playerIndex&&isPlayed(r.score));const total=played.reduce((s,r)=>s+r.score,0);return{name,playerIndex,played:played.length,total,average:played.length?total/played.length:null,best:played.length?Math.max(...played.map(r=>r.score)):null}})}
function getRanking(stats){return[...stats].sort((a,b)=>b.total-a.total||(b.average??-1)-(a.average??-1)||a.playerIndex-b.playerIndex)}
function renderStandings(ranking){const tbody=document.getElementById("standingsBody");tbody.innerHTML="";ranking.forEach((p,i)=>{const row=document.createElement("tr");row.innerHTML=`<td data-label="Plats" class="${i===0?"rank--top":""}">${i+1}</td><td data-label="Spelare" class="player-name">${p.name}</td><td data-label="Spelade">${p.played}/6</td><td data-label="Totalt" class="total">${p.total}</td><td data-label="Snitt">${p.average===null?"–":p.average.toFixed(2)}</td><td data-label="Bäst">${p.best??"–"}</td>`;tbody.appendChild(row)})}
function renderRounds(schedule){const tbody=document.getElementById("roundsBody");tbody.innerHTML="";const nextIndex=schedule.findIndex(r=>!isPlayed(r.score));schedule.forEach((r,i)=>{let t="Kommande",c="status status--upcoming";const row=document.createElement("tr");if(isPlayed(r.score)){t="Spelad";c="status status--played"}else if(i===nextIndex){t="Nästa";c="status status--next";row.classList.add("next-round")}row.innerHTML=`<td data-label="Omgång">${r.round}</td><td data-label="Vecka">v.${r.week}</td><td data-label="År">${r.year}</td><td data-label="Spelare" class="player-name">${r.playerName}</td><td data-label="Resultat" class="${isPlayed(r.score)?"":"score-empty"}">${isPlayed(r.score)?r.score:"–"}</td><td data-label="Status"><span class="${c}">${t}</span></td>`;tbody.appendChild(row)})}
function renderHistory(){const grid=document.getElementById("historyGrid");grid.innerHTML="";[...previousSeasons].reverse().forEach(item=>{const el=document.createElement("div");el.className="history-item";el.innerHTML=`<span class="history-season">${item.season}</span><span class="${item.winner?"history-winner":"history-empty"}">${item.winner??"Ej angiven"}</span>`;grid.appendChild(el)})}
function renderSummary(schedule,ranking){const played=schedule.filter(r=>isPlayed(r.score));const next=schedule.find(r=>!isPlayed(r.score));const leader=ranking.find(p=>p.played>0);document.getElementById("leaderName").textContent=leader?leader.name:"Ingen ännu";document.getElementById("leaderScore").textContent=leader?`${leader.total} poäng`:"0 poäng";if(next){document.getElementById("nextPlayer").textContent=next.playerName;document.getElementById("nextRound").textContent=`Omgång ${next.round} · v.${next.week} ${next.year}`}if(played.length){const best=played.reduce((a,b)=>b.score>a.score?b:a);document.getElementById("bestRound").textContent=`${best.score} rätt`;document.getElementById("bestRoundPlayer").textContent=`${best.playerName}, v.${best.week} ${best.year}`}const first=schedule[0],last=schedule[schedule.length-1];const n=first.year===last.year?`${first.year}`:`${first.year}/${last.year}`;document.getElementById("seasonLabel").textContent=`Stryktipset ${n}`;document.getElementById("seasonRange").textContent=n;document.getElementById("seasonWeeks").textContent=`v.${first.week} ${first.year} – v.${last.week} ${last.year}`;document.getElementById("footerSeason").textContent=n}
const schedule=getSchedule();const ranking=getRanking(buildStats(schedule));renderStandings(ranking);renderHistory();renderRounds(schedule);renderSummary(schedule,ranking);
